server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/task_user-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/